### ISSUE TITLE
Sync metadata isn't doing a git pull on prod

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/tinker#255]

**Comment by phg49389** [comment]
It looks like tinker/tinker/admin/sync/__init__.py has the git_pull() calls commented out since they were breaking tinkerXP. The method itself is located in tinker/tinker/admin/sync/sync_controller.py. Perhaps the fix we need is to call "git branch" and check if it's on master branch, and only if it is do we call "sudo -u apache git pull"?

**Comment by c-schwarze** [comment]
Added that back in.

Closing
